version: '3.8'

services:
  template:
    build: ./backend
    container_name: template_container
    ports:
      - "8080:8000"
    volumes:
      - ./backend:/app
    restart: unless-stopped

volumes:
  logs:
